import type { Player } from "~/types/base";

export const sampleTeam: Player[] = [
  {
    name: "forward1",
    age: 25,
    gender: "male",
    Dominant: "right",
    position: "forward",
    role: "captain",
  },
  {
    name: "forward2",
    age: 30,
    gender: "male",
    Dominant: "left",
    position: "forward",
    role: "vice-captain",
  },
  {
    name: "forward3",
    age: 27,
    gender: "female",
    Dominant: "right",
    position: "forward",
    role: "none",
  },
  {
    name: "midfielder1",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "midfielder",
    role: "none",
  },
  {
    name: "midfielder2",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "midfielder",
    role: "none",
  },
  {
    name: "midfielder3",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "midfielder",
    role: "none",
  },
  {
    name: "midfielder4",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "midfielder",
    role: "none",
  },
  {
    name: "defender1",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "defender",
    role: "none",
  },
  {
    name: "defender2",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "defender",
    role: "none",
  },
  {
    name: "defender3",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "defender",
    role: "none",
  },
  {
    name: "goalkeeper",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "goalkeeper",
    role: "none",
  },
  {
    name: "hikae1",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "forward",
    role: "none",
  },
  {
    name: "hikae2",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "forward",
    role: "none",
  },
  {
    name: "hikae3",
    age: 20,
    gender: "male",
    Dominant: "right",
    position: "forward",
    role: "none",
  },
];

export const sampleOpponentTeam: Player[] = [
  {
    name: "sister-1",
    age: 25,
    gender: "male",
    Dominant: "right",
    position: "forward",
    role: "captain",
  },
]
