import type { Player } from '~/types/base';

export const sampleTeam: Player[] = [
  {
    id: 1,
    name: 'forward1',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'forward',
    role: 'captain',
  },
  {
    id: 1,
    name: 'forward2',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'left',
    position: 'forward',
    role: 'vice-captain',
  },
  {
    id: 1,
    name: 'forward3',
    birthdate: new Date('2000-01-01'),
    gender: 'female',
    dominant: 'right',
    position: 'forward',
    role: 'none',
  },
  {
    id: 1,
    name: 'midfielder1',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'midfielder',
    role: 'none',
  },
  {
    id: 1,
    name: 'midfielder2',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'midfielder',
    role: 'none',
  },
  {
    id: 1,
    name: 'midfielder3',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'midfielder',
    role: 'none',
  },
  {
    id: 1,
    name: 'midfielder4',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'midfielder',
    role: 'none',
  },
  {
    id: 1,
    name: 'defender1',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'defender',
    role: 'none',
  },
  {
    id: 1,
    name: 'defender2',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'defender',
    role: 'none',
  },
  {
    id: 1,
    name: 'defender3',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'defender',
    role: 'none',
  },
  {
    id: 1,
    name: 'goalkeeper',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'goalkeeper',
    role: 'none',
  },
  {
    id: 1,
    name: 'hikae1',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'forward',
    role: 'none',
  },
  {
    id: 1,
    name: 'hikae2',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'forward',
    role: 'none',
  },
  {
    id: 1,
    name: 'hikae3',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'forward',
    role: 'none',
  },
];

export const sampleOpponentTeam: Player[] = [
  {
    id: 1,
    name: 'sister-1',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    dominant: 'right',
    position: 'forward',
    role: 'captain',
  },
];
